version: '3.1'

services:
    database:
        image: mongo
        container_name: database
        environment:
            - MONGO_INITDB_DATABASE=cryptotweets
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=secret
        volumes:
            - ./docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./docker/mongo/volume:/data/db
        ports:
            - '27017-27019:27017-27019'